name: Release Tests & Publish

on:
  release:
    types: [ 'published' ]

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout for CI 🛎️'
        uses: actions/checkout@v4
      - name: 'Set up JDK 21 📦'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: 'Build with Gradle 🏗️'
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build test publish
        env:
          RELEASES_MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          RELEASES_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: 'Publish Test Report 📊'
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # Continue on failure
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/build/libs/*.jar
          tag_name: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}